### ISSUE TITLE
Beginner Friendly - Add table loading state

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#10]
Summary: Since our backend is hosted on Google App Engine it sometimes takes 7-8 seconds for data to come back from the server.  We want to add a material-ui loading state where the TableBody is before the data populates.

Some example steps to solve this would be:
- [ ] Add boolean state variable `loadingProjects` and set to true initially

- [ ] while true, show loading state, preferably a darkPurple https://material-ui.com/demos/progress/#linear-indeterminate

- [ ] location of loading state should be where the TableBody is, right under the TableHead

- [ ] when data comes back, set state variable to false so table is rendered.

**Comment by felipemfp** [comment]
Could I give a try?

**Comment by TheWillG** [comment]
@felipemfp it’s all you!
