### ISSUE TITLE
"NEW" label

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#14]
The projects will eventually come back with a dateCreated field on them in GMT form. Take this date field and if the project is less than 5 days old, add a "NEW" button/label in a new column to the left of the "Name" column.

- [ ] Figure out if a project is new by checking the dateCreated timestamp. Project is new if it is less than 5 days old

- [ ] All new projects will get a yellow button with black text to the left of the name, and button/label will say NEW

**Comment by B1tF8er** [comment]
Hello, Could I start working on this?

**Comment by adamk1230** [comment]
I've submitted a PR.
