### ISSUE TITLE
Landing page for newcomers

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#17]
We need a landing page to help describe to newcomers what our site is all about.

- [ ] Create new component called Landing and have route `/` automatically go to Landing.

- [ ] Have a call to action button in the middle of the screen link to the `Home` component

- [ ] The text on the landing page can be something to the effect:
```
CodeRally
Get experience by building real apps with a real team

<button>Get Started</button>
```

**Comment by shubhamguptaji** [comment]
can i fix this issue?

**Comment by razi-ed** [comment]
Is this Issue taken? Can I contribute?

**Comment by TheWillG** [comment]
If you want feel free to submit a PR

**Comment by TheWillG** [comment]
It would be awesome to have the second line of text animated so it looks like somebody is typing it! If you can't that's okay, I will probably add it at some point
