### ISSUE TITLE
New label is too close to project name

### ISSUE THREAD

**Issue by theblindprophet** [TheWillG/CodeRally#21]
And in my design, opinion, the new label is a little too big.

![screen shot 2018-10-05 at 12 23 56 pm](https://user-images.githubusercontent.com/7903413/46547249-5a93fe80-c899-11e8-8505-20378ad8735e.png)

**Comment by TheWillG** [comment]
Also let's make NEW **bold**.

**Comment by antonlopez** [comment]
I'll work on this

**Comment by TheWillG** [comment]
All you @antonlopez
