### ISSUE TITLE
Add Slack/Gitter link to input form

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#25]
- [ ] Add Slack/Gitter link to input form using the state variable `chatLink`

**Comment by lndgalante** [comment]
Hi @TheWillG you need only one input for both slack and gitter?

**Comment by TheWillG** [comment]
@lndgalante that's what I was thinking, what do you recommend? I figured most projects would only have one or the other

**Comment by lndgalante** [comment]
Yep I imagine the same @TheWillG it's not common to have two chat sources.

**Comment by TheWillG** [comment]
the backend is already setup to handle `chatLink`

**Comment by TheWillG** [comment]
Also, if possible, we also need to render that chatLink property on the Product page

**Comment by lndgalante** [comment]
Great, what about the validation of the url? We need a `validateChatLink` function?

**Comment by TheWillG** [comment]
Yeah I would use the same validation as the website or link property

**Comment by TheWillG** [comment]
Which is essentially just a HTTPS URL regex.
