### ISSUE TITLE
Design - Improve Project Page

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#28]
- [ ] The Project page is boring and needs a better design. Icons, larger font, anything is fair game (except clashing with the existing color scheme).  

As always clean code and best practices are a must.

**Comment by mahamshahid18** [comment]
Hey @TheWillG I'd like to work on this

**Comment by TheWillG** [comment]
@mahamshahid18 All yours!

**Comment by vinird** [comment]
Hi @TheWillG , I want to propose a second option, then you can choose ;)

**Comment by TheWillG** [comment]
@vinird go for it!

**Comment by Vishal1541** [comment]
@TheWillG I also want to take this issue! :smiley:

**Comment by TheWillG** [comment]
@Vishal1541 go for it. Please submit a PR when finished

**Comment by Vishal1541** [comment]
@TheWillG Please refer to the PR #31 

![css](https://user-images.githubusercontent.com/20883811/46579626-20f6fb00-ca33-11e8-86c1-94b75d81dd34.png)

**Comment by mahamshahid18** [comment]
Hey @TheWillG you can take a look at this design as well, in case you like it. I know you closed the issue but I was already working on it so I thought I should complete it :) (ref: PR created above)
