### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#3]
What we are looking for is basic form validation for URLs on the form. If the URL is not a valid HTTPS URL show an error hint under the input.

- [ ] Apply client side form validation to the Add Project Form.

**Comment by shaminmeerankutty** [comment]
@TheWillG May be I can help with this one.

**Comment by TheWillG** [comment]
@shaminmeerankutty go for it! Let me know if you have any issues.

**Comment by TheWillG** [comment]
Correct. We can change it later but I think restricting to HTTPS will work

**Comment by TheWillG** [comment]
Maybe also add a GitHub repo url input since I think right now we are only accepting a website input.
