### ISSUE TITLE
Input form tech chips 

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#33]
The input form must accept techs in the form of chips. This will require allowing the user to type a tech, press the enter key, and show the tech as a chip on the form. If the user adds multiple techs, there should be multiple chips. The form should then submit the techs as an array of strings. 

The second part of this issue would be displaying the chips on the project page since they will come back as a string array.

**Comment by TheWillG** [comment]
@mahamshahid18

**Comment by mahamshahid18** [comment]
I'll start on this soon 👍

**Comment by TheWillG** [comment]
@thakursaurabh1998 go for it! I will create an equivalent issue for the backend.

**Comment by TheWillG** [comment]
Here is the equivalent work item for the backend https://github.com/TheWillG/CodeRally-API/issues/6. I will merge both at the same time.

**Comment by thakursaurabh1998** [comment]
What I wanted to do is let's keep storing the tech data in form of string 
like: `tech: "React, Express, Node"`
And we can parse the array in the front end by splitting the string directly.
And also for posting we will create a string as said above and send the same string to the server.
This will save the time and we won't have to change the backend and the already saved database documents.

**Comment by TheWillG** [comment]
@thakursaurabh1998 I wanted the stored data structure to be the same but I guess this makes sense since the schema is already there on the backend, no need to change it. Alright, carry on.

**Comment by thakursaurabh1998** [comment]
I have completed it.
Here are some screenshots.
![image](https://user-images.githubusercontent.com/18613564/46762584-19ff0f80-ccf5-11e8-9f77-bac415c4fbff.png)
![image](https://user-images.githubusercontent.com/18613564/46762612-2a16ef00-ccf5-11e8-9343-7bd0a4d86304.png)

**Comment by TheWillG** [comment]
@thakursaurabh1998 looks clean!!

**Comment by TheWillG** [comment]
@thakursaurabh1998 I'm wondering if it would look better with the chips under the input, or possibly inside the input itself?

**Comment by thakursaurabh1998** [comment]
@TheWillG I don't think inside the input box will be possible as Material UI doesn't have support for that type of component. 
Anyhow do you like this?
![image](https://user-images.githubusercontent.com/18613564/46763088-862e4300-ccf6-11e8-90ce-dc31e163324b.png)

**Comment by TheWillG** [comment]
Yup, looks good to me.

**Comment by thakursaurabh1998** [comment]
Should I submit a PR now?
@TheWillG

**Comment by TheWillG** [comment]
Sure
