### ISSUE TITLE
Sort when Tech chip clicked

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#35]
- [ ] Make Tech chips on table clickable

- [ ] When clicking Tech chip, highlight this clicked chip and add the chip under the "Search" bar to show that this chip is being added to the search.

- [ ] Sort using the chip value on top of the existing search bar

- [ ] Also, pick your favorite open source project and add it to the app!!

Use clean code and best practices.

**Comment by klanti117** [comment]
would like to work on it

**Comment by TheWillG** [comment]
@klanti117 all yours

**Comment by thakursaurabh1998** [comment]
I think I can solve this. And moreover the solution by @Smith2106 seems to be not ideal. Kindly tell me if it needs working or not @TheWillG

**Comment by TheWillG** [comment]
@thakursaurabh1998 go for it!
