### ISSUE TITLE
Beginner Friendly - Add repo as form input

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#6]
Summary: Add Repo URL as a form input and name the state variable `repoLink`.  

- [ ] Add Repo Link as form input and capture inside state variable `repoLink`

- [ ] Validate that the Repo URL is a valid Git repository URL (AKA `git@` or `https://`)

**Comment by Jayadev6191** [comment]
Is this still available. Can I take this ? :)

**Comment by TheWillG** [comment]
@Jayadev6191 it's all yours!

**Comment by Jayadev6191** [comment]
@TheWillG Raised a PR [(#7](https://github.com/TheWillG/CodeRally/pull/7) )
