### ISSUE TITLE
Add Table Filtering

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/CodeRally#9]
**Summary**: Using material-ui, add a search bar on top of the table and search the following fields: name, description, and technology. It should filter the list in real-time as they type.

- [ ] Add search input on top of table

- [ ] Search on the following fields: name, description, and technology

- [ ] Use material-ui so the search bar looks nice and follows the existing theme

As always, use clean code and best practices.

**Comment by yogs22** [comment]
can i contributed ?

**Comment by yogs22** [comment]
Oke,, on progress :+1:

**Comment by yogs22** [comment]
i just can add input, but not filtered
may i make e pull request ?

**Comment by yogs22** [comment]
i was finished this issue
